// <auto-generated />
using System;
using FaceRecApp.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FaceRecApp.Core.Migrations
{
    [DbContext(typeof(FaceDbContext))]
    [Migration("20260325144355_SplitBiometricTables")]
    partial class SplitBiometricTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FaceRecApp.Core.Entities.FaceEmbedding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CaptureAngle")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Consent")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.PrimitiveCollection<string>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(512)");

                    b.Property<byte[]>("FaceThumbnail")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PID")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("PID");

                    b.Property<float?>("QualityScore")
                        .HasColumnType("real");

                    b.Property<string>("Remark")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("PID");

                    b.ToTable("FaceEmbeddings", (string)null);
                });

            modelBuilder.Entity("FaceRecApp.Core.Entities.FingerprintTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CaptureDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Consent")
                        .HasColumnType("bit");

                    b.Property<string>("ConsentRefusalReason")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FingerType")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PID")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("PID");

                    b.Property<string>("Remark")
                        .HasColumnType("varchar(100)");

                    b.Property<byte[]>("Template")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("FingerType");

                    b.HasIndex("PID");

                    b.ToTable("FingerprintTemplates", (string)null);
                });

            modelBuilder.Entity("FaceRecApp.Core.Entities.Patient", b =>
                {
                    b.Property<string>("IDCard")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("AddressCode")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AddressOther")
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime?>("AdmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("Age")
                        .HasColumnType("tinyint");

                    b.Property<string>("BurmeseName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CreatedOn")
                        .HasColumnType("varchar(50)");

                    b.Property<short?>("DOB_day")
                        .HasColumnType("smallint");

                    b.Property<short?>("DOB_month")
                        .HasColumnType("smallint");

                    b.Property<short?>("DOB_year")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Day")
                        .HasColumnType("tinyint");

                    b.Property<string>("FatherName")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FullName")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("KarenName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastSync")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ModifiedOn")
                        .HasColumnType("varchar(50)");

                    b.Property<byte?>("Month")
                        .HasColumnType("tinyint");

                    b.Property<string>("MotherName")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MotherPID")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Note")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(50)");

                    b.Property<byte?>("Sex")
                        .HasColumnType("tinyint");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("SpouseName")
                        .HasColumnType("varchar(100)");

                    b.HasKey("IDCard");

                    b.HasIndex("FullName");

                    b.HasIndex("Site");

                    b.ToTable("Patients", (string)null);
                });

            modelBuilder.Entity("FaceRecApp.Core.Entities.RecognitionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Distance")
                        .HasColumnType("real");

                    b.Property<string>("PID")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("PID");

                    b.Property<bool>("PassedLiveness")
                        .HasColumnType("bit");

                    b.Property<string>("StationId")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<bool>("WasRecognized")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PID");

                    b.HasIndex("Timestamp");

                    b.HasIndex("WasRecognized");

                    b.ToTable("RecognitionLogs", (string)null);
                });

            modelBuilder.Entity("FaceRecApp.Core.Entities.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChiefComplaint")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("CC");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PID")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("PID");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("PID");

                    b.HasIndex("ServiceType");

                    b.ToTable("Visits", (string)null);
                });

            modelBuilder.Entity("FaceRecApp.Core.Entities.FaceEmbedding", b =>
                {
                    b.HasOne("FaceRecApp.Core.Entities.Patient", "Patient")
                        .WithMany("FaceEmbeddings")
                        .HasForeignKey("PID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("FaceRecApp.Core.Entities.FingerprintTemplate", b =>
                {
                    b.HasOne("FaceRecApp.Core.Entities.Patient", "Patient")
                        .WithMany("FingerprintTemplates")
                        .HasForeignKey("PID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("FaceRecApp.Core.Entities.RecognitionLog", b =>
                {
                    b.HasOne("FaceRecApp.Core.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("FaceRecApp.Core.Entities.Visit", b =>
                {
                    b.HasOne("FaceRecApp.Core.Entities.Patient", "Patient")
                        .WithMany("Visits")
                        .HasForeignKey("PID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("FaceRecApp.Core.Entities.Patient", b =>
                {
                    b.Navigation("FaceEmbeddings");

                    b.Navigation("FingerprintTemplates");

                    b.Navigation("Visits");
                });
#pragma warning restore 612, 618
        }
    }
}
